import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import '../src/assets/index.css'
import './assets/gymman.jpg'
import './assets/bg.jpg'
import './assets/service1.jpg'
import './assets/service2.jpg'
import './assets/service3.jpg'
import './assets/service4.jpg'
import './assets/service5.jpg'
import './assets/service6.jpg'
import './assets/gymlogo.jpg'
import './assets/login1.css'
import './assets/login2.css'
import './assets/navbar.css'
import './assets/hero.css'
import './assets/memberships.css'
import './assets/services.css'
import './assets/aboutus.css'
import './assets/fitnessfooter.css'
import './assets/home.css'
import './assets/bmi.css'
import './assets/trainer.css'
import './assets/diet.css'
import './assets/workout.css'
import './admin/admnav.css'
import './assets/lungs.css'
import './assets/shuttle.css'
import './assets/bronco.css'
import './assets/yoyo.css'
import './assets/cooper.css'
import './assets/illinois.css'
import './assets/shop.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
     <App />
  </StrictMode>,
)
